services:
  packer:
    image: hashicorp/packer:1.14.1
    container_name: build-ami
    working_dir: /packer
    volumes:
      - ./terraform/prerequisite/packer/mongodb-ami:/packer
    env_file:
      - .env
    entrypoint: sh
    tty: true
    stdin_open: true
    command: -c "
      packer init . && 
      packer validate . && 
      packer build ."

  terraform:
    image: hashicorp/terraform:1.13.1
    working_dir: /terraform/apps
    volumes:
      - ./terraform:/terraform:rw
    env_file:
      - .env
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
    command: -c "
      terraform init -upgrade && 
      terraform fmt && 
      terraform validate &&
      terraform plan &&
      terraform apply -auto-approve &&
      /bin/sh"
