services:
  packer:
    image: hashicorp/packer:1.14.1
    container_name: build-ami
    working_dir: /packer
    volumes:
      - ./terraform/prerequisite/mongodb-ami:/packer
    env_file:
      - .env
    entrypoint: sh
    tty: true
    stdin_open: true
    command: -c "
      packer init . && 
      packer validate . && 
      packer build . && 
      sh"

  terraform:
    image: hashicorp/terraform:1.13.1
    working_dir: /terraform
    volumes:
      - ./terraform:/terraform:rw
      - ~/.ssh:/root/.ssh:ro
    env_file:
      - .env
    entrypoint: /bin/sh
    tty: true
    stdin_open: true
    command: -c "
      cd ./infra && 
      terraform init -upgrade && 
      terraform fmt && 
      terraform validate &&
      terraform plan -out plan &&
      terraform apply "plan" &&
      /bin/sh"

# Project Execution Steps: Change the directory and plan's name before executing commands below.
# docker compose run --rm --name packer-net terraform
# docker compose run --rm --name build-ami packer
# docker compose run --rm --name infra terraform
# docker compose run --rm --name platform terraform