name: Build and Push WebApp Image

on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./webapp/Dockerfile
          context: ./webapp
          tags: |
            ghcr.io/${{ github.repository }}/webapp:latest
            ghcr.io/${{ github.repository }}/webapp:${{ github.sha }}
